export interface Location {
  name: string;
  slug: string;
  state: 'TX';
  county: string;
  population: number;
  zipCodes: string[];
  neighborhoods: string[];
  landmarks: string[];
  metaTitle: string;
  metaDescription: string;
}

export const locations: Location[] = [
  {
    name: 'Austin',
    slug: 'austin-tx',
    state: 'TX',
    county: 'Travis',
    population: 978908,
    zipCodes: ['78701', '78702', '78703', '78704', '78705', '78741', '78745', '78748', '78749', '78750'],
    neighborhoods: ['South Congress', 'East Austin', 'Hyde Park', 'Bouldin Creek', 'Mueller', 'Barton Hills'],
    landmarks: ['University of Texas at Austin', 'Dell Technologies HQ', 'Tesla Gigafactory'],
    metaTitle: 'Sell My House Fast Austin TX | Cash Offer in 24 Hours – Elevate Home Offers',
    metaDescription: 'Need to sell your house fast in Austin, TX? Elevate Home Offers pays cash for homes in any condition. No fees, no repairs, close in 7 days. Get your free offer today.',
  },
  {
    name: 'Round Rock',
    slug: 'round-rock-tx',
    state: 'TX',
    county: 'Williamson',
    population: 133372,
    zipCodes: ['78664', '78665', '78681'],
    neighborhoods: ['Brushy Creek', 'Stone Oak', 'Teravista', 'Forest Creek', 'Walsh Ranch', 'Highlands at Mayfield Ranch'],
    landmarks: ['Dell Technologies Campus', 'Round Rock Premium Outlets', 'Dell Diamond Stadium'],
    metaTitle: 'Sell My House Fast Round Rock TX | Cash Buyers – Elevate Home Offers',
    metaDescription: 'Sell your house fast in Round Rock, TX for cash. Elevate Home Offers buys homes as-is with no fees or commissions. Get a fair cash offer in 24 hours.',
  },
  {
    name: 'Leander',
    slug: 'leander-tx',
    state: 'TX',
    county: 'Williamson',
    population: 75893,
    zipCodes: ['78641', '78646'],
    neighborhoods: ['Crystal Falls', 'Travisso', 'Bryson', 'Mason Hills', 'Grand Mesa', 'Horizon Park'],
    landmarks: ['Leander MetroRail Station', 'Crystal Falls Golf Club', 'Lake Travis'],
    metaTitle: 'Sell My House Fast Leander TX | Cash Home Buyers – Elevate Home Offers',
    metaDescription: 'Sell your Leander, TX home fast for cash. No repairs, no commissions, close in as little as 7 days. Call Elevate Home Offers for a free no-obligation cash offer.',
  },
  {
    name: 'Georgetown',
    slug: 'georgetown-tx',
    state: 'TX',
    county: 'Williamson',
    population: 86400,
    zipCodes: ['78626', '78627', '78628', '78633'],
    neighborhoods: ['Sun City Texas', 'Teravista', 'Wolf Ranch', 'Georgetown Village', 'Cimarron Hills', 'Berry Creek'],
    landmarks: ['Georgetown Square', 'Southwestern University', 'Inner Space Cavern'],
    metaTitle: 'Sell My House Fast Georgetown TX | Cash Offers – Elevate Home Offers',
    metaDescription: 'Need to sell your Georgetown, TX house fast? We buy homes for cash in any condition. No fees, no repairs, close in 7 days. Get your free offer from Elevate Home Offers.',
  },
  {
    name: 'Cedar Park',
    slug: 'cedar-park-tx',
    state: 'TX',
    county: 'Williamson',
    population: 82453,
    zipCodes: ['78613', '78630'],
    neighborhoods: ['Ranch at Brushy Creek', 'Twin Creeks', 'Buttercup Creek', 'Caballo Ranch', 'Anderson Mill West', 'Whitestone'],
    landmarks: ['HEB Center at Cedar Park', 'Top Golf Cedar Park', 'Lake Travis'],
    metaTitle: 'Sell My House Fast Cedar Park TX | Cash Home Buyers – Elevate Home Offers',
    metaDescription: 'Sell your Cedar Park home for cash fast. Elevate Home Offers buys houses as-is with no agent fees. Get a fair cash offer in 24 hours and close in 7 days.',
  },
  {
    name: 'Pflugerville',
    slug: 'pflugerville-tx',
    state: 'TX',
    county: 'Travis',
    population: 72038,
    zipCodes: ['78660', '78691'],
    neighborhoods: ['Blackhawk', 'Swenson Farm', 'Sorento', 'Highland Park', 'Wells Branch', 'Spring Trails'],
    landmarks: ['Typhoon Texas Waterpark', 'Lake Pflugerville', 'Stone Hill Town Center'],
    metaTitle: 'Sell My House Fast Pflugerville TX | Cash Buyers – Elevate Home Offers',
    metaDescription: 'We buy houses fast in Pflugerville, TX for cash. No repairs, no commissions, no hassle. Get a free cash offer from Elevate Home Offers in 24 hours.',
  },
  {
    name: 'Kyle',
    slug: 'kyle-tx',
    state: 'TX',
    county: 'Hays',
    population: 72698,
    zipCodes: ['78640'],
    neighborhoods: ['Plum Creek', 'Hometown Kyle', 'Trace', 'Waterleaf', '6 Creeks', 'Jordan Crossing'],
    landmarks: ['Seton Medical Center Hays', 'Kyle Marketplace', 'Plum Creek Golf Course'],
    metaTitle: 'Sell My House Fast Kyle TX | Cash Home Offers – Elevate Home Offers',
    metaDescription: 'Sell your Kyle, TX house fast for cash. Elevate Home Offers buys homes in any condition with no fees or repairs needed. Get your free offer today.',
  },
  {
    name: 'Hutto',
    slug: 'hutto-tx',
    state: 'TX',
    county: 'Williamson',
    population: 35820,
    zipCodes: ['78634'],
    neighborhoods: ['Star Ranch', 'Riverview', 'Emory Farms', 'Brushy Creek Farms', 'Cottonwood Creek', 'Carriage Hills'],
    landmarks: ['Samsung Austin Semiconductor', 'Hutto Community Park', 'Williamson County Regional Park'],
    metaTitle: 'Sell My House Fast Hutto TX | Cash Offers – Elevate Home Offers',
    metaDescription: 'Need to sell your Hutto, TX home quickly? We buy houses for cash with no repairs or fees. Close in 7 days. Get a free no-obligation offer from Elevate Home Offers.',
  },
  {
    name: 'Buda',
    slug: 'buda-tx',
    state: 'TX',
    county: 'Hays',
    population: 27800,
    zipCodes: ['78610'],
    neighborhoods: ['Whispering Hollow', 'Garlic Creek', 'Sunfield', 'Elm Grove', 'Leisure Lake', 'Ruby Ranch'],
    landmarks: ['Cabela\'s Buda', 'Old Town Buda', 'Onion Creek'],
    metaTitle: 'Sell My House Fast Buda TX | Cash Home Buyers – Elevate Home Offers',
    metaDescription: 'Sell your Buda, TX house fast for cash. No agent fees, no repairs, close on your schedule. Elevate Home Offers makes fair cash offers in 24 hours.',
  },
  {
    name: 'Manor',
    slug: 'manor-tx',
    state: 'TX',
    county: 'Travis',
    population: 16479,
    zipCodes: ['78653'],
    neighborhoods: ['Shadowglen', 'Whisper Valley', 'Stonewater', 'Presidential Meadows', 'Wildhorse', 'Edgewater'],
    landmarks: ['Walter E. Long Metropolitan Park', 'Manor New Tech High School', 'Austin Colony Golf Course'],
    metaTitle: 'Sell My House Fast Manor TX | Cash Buyers – Elevate Home Offers',
    metaDescription: 'We buy houses in Manor, TX for cash fast. No commissions, no repairs, close in as little as 7 days. Get your free cash offer from Elevate Home Offers today.',
  },
  {
    name: 'Temple',
    slug: 'temple-tx',
    state: 'TX',
    county: 'Bell',
    population: 82073,
    zipCodes: ['76501', '76502', '76503', '76504', '76508'],
    neighborhoods: ['Adams Ranch', 'Lakewood', 'Midway Estates', 'Belton Lake Estates', 'Stuart Place', 'Heritage'],
    landmarks: ['Baylor Scott & White Medical Center', 'Temple College', 'Stillhouse Hollow Lake'],
    metaTitle: 'Sell My House Fast Temple TX | Cash Home Offers – Elevate Home Offers',
    metaDescription: 'Sell your Temple, TX house for cash fast. Elevate Home Offers buys homes as-is with no fees or hassle. Get a fair cash offer within 24 hours.',
  },
  {
    name: 'Killeen',
    slug: 'killeen-tx',
    state: 'TX',
    county: 'Bell',
    population: 153095,
    zipCodes: ['76541', '76542', '76543', '76544', '76549'],
    neighborhoods: ['Trimmier Estates', 'Yowell Ranch', 'Willow Spring', 'Westcliff', 'Lake House', 'Pershing Park'],
    landmarks: ['Fort Cavazos (Fort Hood)', 'Central Texas College', 'Killeen-Fort Hood Regional Airport'],
    metaTitle: 'Sell My House Fast Killeen TX | Cash Buyers – Elevate Home Offers',
    metaDescription: 'Need to sell your Killeen, TX home fast? We buy houses near Fort Cavazos and throughout Killeen for cash. No fees, no repairs. Get your offer in 24 hours.',
  },
  {
    name: 'Taylor',
    slug: 'taylor-tx',
    state: 'TX',
    county: 'Williamson',
    population: 16353,
    zipCodes: ['76574'],
    neighborhoods: ['Murphy Park', 'Taylor Town Square', 'Tiffany Estates', 'Westwood', 'Heritage Square', 'Ranch Road Estates'],
    landmarks: ['Samsung Taylor Semiconductor Campus', 'Murphy Park', 'Taylor Heritage Museum'],
    metaTitle: 'Sell My House Fast Taylor TX | Cash Home Buyers – Elevate Home Offers',
    metaDescription: 'Sell your Taylor, TX house fast for cash. With Samsung\'s new campus nearby, now is a great time to sell. No fees, no repairs. Get your free offer from Elevate Home Offers.',
  },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return locations.find((loc) => loc.slug === slug);
}
